; generated by tools/zxgfx.py from tools/zxart.py - do not edit
gfx_track_table:
                defw gfx_track_rail_a
                defw gfx_track_rail_b
                defw gfx_track_stop_0
                defw gfx_track_stop_1
                defw gfx_track_signal_0
                defw gfx_track_signal_1
                defw gfx_track_wagon1_end_bottom
                defw gfx_track_wagon1_body_a
                defw gfx_track_wagon1_body_b
                defw gfx_track_wagon1_end_top
                defw gfx_track_wagon1_coupler
                defw gfx_track_wagon2_end_bottom
                defw gfx_track_wagon2_body_a
                defw gfx_track_wagon2_body_b
                defw gfx_track_wagon2_end_top
                defw gfx_track_wagon2_coupler
                defw gfx_track_wagon3_end_bottom
                defw gfx_track_wagon3_body_a
                defw gfx_track_wagon3_body_b
                defw gfx_track_wagon3_end_top
                defw gfx_track_wagon3_coupler
                defw gfx_track_loco1_nose
                defw gfx_track_loco1_body
                defw gfx_track_loco1_pantograph
                defw gfx_track_loco1_nose_top
                defw gfx_track_loco2_nose
                defw gfx_track_loco2_body
                defw gfx_track_loco2_pantograph
                defw gfx_track_loco2_nose_top
                defw gfx_track_loco3_nose
                defw gfx_track_loco3_body
                defw gfx_track_loco3_pantograph
                defw gfx_track_loco3_nose_top
                defw gfx_track_ramp_up_0
                defw gfx_track_ramp_up_1
                defw gfx_track_ramp_up_2
                defw gfx_track_ramp_down_0
                defw gfx_track_ramp_down_1
                defw gfx_track_ramp_down_2
IDX_TRACK_RAIL_A equ 0
gfx_track_rail_a:
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#FF,#FF,#F8,#06,#00,#00,#60
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#FF,#FF,#F8,#06,#00,#00,#60
                defb #47,#07,#07,#47
IDX_TRACK_RAIL_B equ 1
gfx_track_rail_b:
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#FF,#FF,#F8,#02,#00,#00,#40
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#FF,#FF,#F8,#06,#00,#00,#60
                defb #47,#07,#07,#47
IDX_TRACK_STOP_0 equ 2
gfx_track_stop_0:
                defb #0F,#00,#00,#F0,#1F,#FF,#FF,#F8,#1F,#00,#00,#F8,#0F,#00,#00,#F0
                defb #06,#00,#00,#60,#1F,#00,#00,#F8,#1F,#00,#00,#F8,#06,#00,#00,#60
                defb #42,#42,#42,#42
IDX_TRACK_STOP_1 equ 3
gfx_track_stop_1:
                defb #06,#00,#00,#60,#1F,#00,#00,#F8,#7F,#FF,#FF,#FE,#63,#8E,#38,#E2
                defb #63,#8E,#38,#E2,#63,#8E,#38,#E2,#7F,#FF,#FF,#FE,#06,#00,#00,#60
                defb #42,#42,#42,#42
IDX_TRACK_SIGNAL_0 equ 4
gfx_track_signal_0:
                defb #06,#00,#00,#60,#3C,#00,#00,#3C,#7E,#00,#00,#7E,#7E,#FF,#FF,#7E
                defb #7E,#FF,#FF,#7E,#3C,#00,#00,#3C,#00,#00,#00,#00,#06,#00,#00,#60
                defb #42,#47,#47,#42
IDX_TRACK_SIGNAL_1 equ 5
gfx_track_signal_1:
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#FF,#FF,#F8,#06,#00,#00,#60
                defb #06,#00,#00,#60,#1F,#FF,#FF,#F8,#1F,#BB,#BB,#F8,#06,#00,#00,#60
                defb #47,#47,#47,#47
IDX_TRACK_WAGON1_END_BOTTOM equ 6
gfx_track_wagon1_end_bottom:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#DF,#FF,#FF,#FB,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #20,#20,#20,#20
IDX_TRACK_WAGON1_BODY_A equ 7
gfx_track_wagon1_body_a:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#1E,#78,#0B,#D0,#12,#48,#0B
                defb #D0,#12,#48,#0B,#D0,#1E,#78,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_WAGON1_BODY_B equ 8
gfx_track_wagon1_body_b:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#7F,#FE,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_WAGON1_END_TOP equ 9
gfx_track_wagon1_end_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#DF,#FF,#FF,#FB,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_WAGON1_COUPLER equ 10
gfx_track_wagon1_coupler:
                defb #00,#04,#20,#00,#00,#04,#20,#00,#00,#05,#A0,#00,#00,#05,#A0,#00
                defb #00,#05,#A0,#00,#00,#05,#A0,#00,#00,#04,#20,#00,#00,#04,#20,#00
                defb #47,#07,#07,#47
IDX_TRACK_WAGON2_END_BOTTOM equ 11
gfx_track_wagon2_end_bottom:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#DF,#FF,#FF,#FB,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #38,#39,#39,#38
IDX_TRACK_WAGON2_BODY_A equ 12
gfx_track_wagon2_body_a:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#1E,#78,#0B,#D0,#12,#48,#0B
                defb #D0,#12,#48,#0B,#D0,#1E,#78,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_WAGON2_BODY_B equ 13
gfx_track_wagon2_body_b:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#7F,#FE,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_WAGON2_END_TOP equ 14
gfx_track_wagon2_end_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#DF,#FF,#FF,#FB,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_WAGON2_COUPLER equ 15
gfx_track_wagon2_coupler:
                defb #00,#04,#20,#00,#00,#04,#20,#00,#00,#05,#A0,#00,#00,#05,#A0,#00
                defb #00,#05,#A0,#00,#00,#05,#A0,#00,#00,#04,#20,#00,#00,#04,#20,#00
                defb #47,#07,#07,#47
IDX_TRACK_WAGON3_END_BOTTOM equ 16
gfx_track_wagon3_end_bottom:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#DF,#FF,#FF,#FB,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #10,#16,#16,#10
IDX_TRACK_WAGON3_BODY_A equ 17
gfx_track_wagon3_body_a:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#1E,#78,#0B,#D0,#12,#48,#0B
                defb #D0,#12,#48,#0B,#D0,#1E,#78,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_WAGON3_BODY_B equ 18
gfx_track_wagon3_body_b:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #D0,#7F,#FE,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_WAGON3_END_TOP equ 19
gfx_track_wagon3_end_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#DF,#FF,#FF,#FB,#D0,#00,#00,#0B
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_WAGON3_COUPLER equ 20
gfx_track_wagon3_coupler:
                defb #00,#04,#20,#00,#00,#04,#20,#00,#00,#05,#A0,#00,#00,#05,#A0,#00
                defb #00,#05,#A0,#00,#00,#05,#A0,#00,#00,#04,#20,#00,#00,#04,#20,#00
                defb #47,#07,#07,#47
IDX_TRACK_LOCO1_NOSE equ 21
gfx_track_loco1_nose:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D7,#FE,#7F,#EB
                defb #C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #20,#20,#20,#20
IDX_TRACK_LOCO1_BODY equ 22
gfx_track_loco1_body:
                defb #D0,#00,#00,#0B,#D0,#FF,#FF,#0B,#D0,#A4,#91,#0B,#D0,#A4,#91,#0B
                defb #D0,#A4,#91,#0B,#D0,#A4,#91,#0B,#D0,#FF,#FF,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_LOCO1_PANTOGRAPH equ 23
gfx_track_loco1_pantograph:
                defb #D0,#08,#10,#0B,#D0,#04,#20,#0B,#D0,#02,#40,#0B,#D3,#FF,#FF,#CB
                defb #D3,#FF,#FF,#CB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_LOCO1_NOSE_TOP equ 24
gfx_track_loco1_nose_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3
                defb #D7,#FE,#7F,#EB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #20,#20,#20,#20
IDX_TRACK_LOCO2_NOSE equ 25
gfx_track_loco2_nose:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D7,#FE,#7F,#EB
                defb #C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #38,#39,#39,#38
IDX_TRACK_LOCO2_BODY equ 26
gfx_track_loco2_body:
                defb #D0,#00,#00,#0B,#D0,#FF,#FF,#0B,#D0,#A4,#91,#0B,#D0,#A4,#91,#0B
                defb #D0,#A4,#91,#0B,#D0,#A4,#91,#0B,#D0,#FF,#FF,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_LOCO2_PANTOGRAPH equ 27
gfx_track_loco2_pantograph:
                defb #D0,#08,#10,#0B,#D0,#04,#20,#0B,#D0,#02,#40,#0B,#D3,#FF,#FF,#CB
                defb #D3,#FF,#FF,#CB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_LOCO2_NOSE_TOP equ 28
gfx_track_loco2_nose_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3
                defb #D7,#FE,#7F,#EB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #38,#39,#39,#38
IDX_TRACK_LOCO3_NOSE equ 29
gfx_track_loco3_nose:
                defb #D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D7,#FE,#7F,#EB
                defb #C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3,#E0,#00,#00,#07,#FF,#FF,#FF,#FF
                defb #10,#16,#16,#10
IDX_TRACK_LOCO3_BODY equ 30
gfx_track_loco3_body:
                defb #D0,#00,#00,#0B,#D0,#FF,#FF,#0B,#D0,#A4,#91,#0B,#D0,#A4,#91,#0B
                defb #D0,#A4,#91,#0B,#D0,#A4,#91,#0B,#D0,#FF,#FF,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_LOCO3_PANTOGRAPH equ 31
gfx_track_loco3_pantograph:
                defb #D0,#08,#10,#0B,#D0,#04,#20,#0B,#D0,#02,#40,#0B,#D3,#FF,#FF,#CB
                defb #D3,#FF,#FF,#CB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_LOCO3_NOSE_TOP equ 32
gfx_track_loco3_nose_top:
                defb #FF,#FF,#FF,#FF,#E0,#00,#00,#07,#C7,#FE,#7F,#E3,#C7,#FE,#7F,#E3
                defb #D7,#FE,#7F,#EB,#D0,#00,#00,#0B,#D0,#00,#00,#0B,#D0,#00,#00,#0B
                defb #10,#16,#16,#10
IDX_TRACK_RAMP_UP_0 equ 33
gfx_track_ramp_up_0:
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#E1,#C0,#03,#87
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#FF,#FF,#FF,#FF
                defb #38,#38,#38,#38
IDX_TRACK_RAMP_UP_1 equ 34
gfx_track_ramp_up_1:
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#E1,#C0,#03,#87
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#E1,#C0,#03,#87
                defb #38,#38,#38,#38
IDX_TRACK_RAMP_UP_2 equ 35
gfx_track_ramp_up_2:
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#E1,#C0,#03,#87
                defb #E2,#00,#00,#47,#E0,#07,#E0,#07,#E0,#38,#1C,#07,#E1,#C0,#03,#87
                defb #38,#38,#38,#38
IDX_TRACK_RAMP_DOWN_0 equ 36
gfx_track_ramp_down_0:
                defb #E2,#00,#00,#47,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #E2,#00,#00,#47,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #38,#38,#38,#38
IDX_TRACK_RAMP_DOWN_1 equ 37
gfx_track_ramp_down_1:
                defb #E2,#00,#00,#47,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #E2,#00,#00,#47,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #38,#38,#38,#38
IDX_TRACK_RAMP_DOWN_2 equ 38
gfx_track_ramp_down_2:
                defb #FF,#FF,#FF,#FF,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #E2,#00,#00,#47,#E1,#C0,#03,#87,#E0,#38,#1C,#07,#E0,#07,#E0,#07
                defb #38,#38,#38,#38
GFX_TRACK_WIDTH equ 4
GFX_TRACK_LINES equ 8
GFX_TRACK_COUNT equ 39
gfx_urban_table:
                defw gfx_urban_road_a
                defw gfx_urban_road_a_m
                defw gfx_urban_road_b
                defw gfx_urban_road_b_m
                defw gfx_urban_road_cross_0
                defw gfx_urban_road_cross_0_m
                defw gfx_urban_road_cross_1
                defw gfx_urban_road_cross_1_m
                defw gfx_urban_road_kiosk_0
                defw gfx_urban_road_kiosk_0_m
                defw gfx_urban_road_kiosk_1
                defw gfx_urban_road_kiosk_1_m
IDX_URBAN_ROAD_A equ 0
gfx_urban_road_a:
                defb #00,#00,#00,#00,#00,#03,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01
                defb #00,#0B,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01,#00,#03,#00,#01
                defb #00,#01,#00,#03,#00,#01,#00,#01,#00,#13,#00,#00,#00,#00,#00,#03
                defb #47,#07,#47,#07,#47,#07
IDX_URBAN_ROAD_A_M equ 1
gfx_urban_road_a_m:
                defb #C0,#00,#00,#00,#00,#00,#C0,#00,#80,#00,#80,#00,#D0,#00,#80,#00
                defb #80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00
                defb #80,#00,#80,#00,#C8,#00,#80,#00,#80,#00,#C0,#00,#00,#00,#00,#00
                defb #07,#47,#07,#47,#07,#47
IDX_URBAN_ROAD_B equ 2
gfx_urban_road_b:
                defb #00,#00,#00,#00,#00,#03,#00,#00,#00,#00,#00,#03,#00,#00,#00,#00
                defb #00,#0B,#00,#00,#00,#00,#00,#03,#00,#00,#00,#00,#00,#03,#00,#00
                defb #00,#00,#00,#03,#00,#00,#00,#00,#00,#13,#00,#00,#00,#00,#00,#03
                defb #47,#47,#47,#47,#47,#07
IDX_URBAN_ROAD_B_M equ 3
gfx_urban_road_b_m:
                defb #C0,#00,#00,#00,#00,#00,#C0,#00,#00,#00,#00,#00,#D0,#00,#00,#00
                defb #00,#00,#C0,#00,#00,#00,#00,#00,#C0,#00,#00,#00,#00,#00,#C0,#00
                defb #00,#00,#00,#00,#C8,#00,#00,#00,#00,#00,#C0,#00,#00,#00,#00,#00
                defb #07,#47,#47,#47,#47,#47
IDX_URBAN_ROAD_CROSS_0 equ 4
gfx_urban_road_cross_0:
                defb #00,#00,#00,#00,#00,#03,#79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79
                defb #E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7
                defb #9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F
                defb #47,#47,#47,#47,#47,#47
IDX_URBAN_ROAD_CROSS_0_M equ 5
gfx_urban_road_cross_0_m:
                defb #C0,#00,#00,#00,#00,#00,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79
                defb #E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7
                defb #9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E
                defb #47,#47,#47,#47,#47,#47
IDX_URBAN_ROAD_CROSS_1 equ 6
gfx_urban_road_cross_1:
                defb #79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79
                defb #E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#79,#E7
                defb #9E,#79,#E7,#9F,#79,#E7,#9E,#79,#E7,#9F,#00,#00,#00,#00,#00,#03
                defb #47,#47,#47,#47,#47,#47
IDX_URBAN_ROAD_CROSS_1_M equ 7
gfx_urban_road_cross_1_m:
                defb #F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79
                defb #E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#F9,#E7
                defb #9E,#79,#E7,#9E,#F9,#E7,#9E,#79,#E7,#9E,#C0,#00,#00,#00,#00,#00
                defb #47,#47,#47,#47,#47,#47
IDX_URBAN_ROAD_KIOSK_0 equ 8
gfx_urban_road_kiosk_0:
                defb #7F,#FE,#00,#00,#00,#03,#60,#06,#00,#01,#00,#03,#6F,#F6,#00,#01
                defb #00,#0B,#60,#06,#00,#01,#00,#03,#60,#06,#00,#01,#00,#03,#7F,#FE
                defb #00,#01,#00,#03,#00,#00,#00,#01,#00,#13,#00,#00,#00,#00,#00,#03
                defb #06,#06,#47,#07,#47,#07
IDX_URBAN_ROAD_KIOSK_0_M equ 9
gfx_urban_road_kiosk_0_m:
                defb #C0,#00,#00,#00,#7F,#FE,#C0,#00,#80,#00,#60,#06,#D0,#00,#80,#00
                defb #6F,#F6,#C0,#00,#80,#00,#60,#06,#C0,#00,#80,#00,#60,#06,#C0,#00
                defb #80,#00,#7F,#FE,#C8,#00,#80,#00,#00,#00,#C0,#00,#00,#00,#00,#00
                defb #07,#47,#07,#47,#06,#06
IDX_URBAN_ROAD_KIOSK_1 equ 10
gfx_urban_road_kiosk_1:
                defb #00,#00,#00,#00,#00,#03,#00,#00,#00,#00,#00,#03,#5B,#6E,#00,#00
                defb #00,#0B,#5B,#6E,#00,#00,#00,#03,#5B,#6E,#00,#00,#00,#03,#5B,#6E
                defb #00,#00,#00,#03,#5B,#6E,#00,#00,#00,#13,#5B,#6E,#00,#00,#00,#03
                defb #06,#06,#47,#47,#47,#07
IDX_URBAN_ROAD_KIOSK_1_M equ 11
gfx_urban_road_kiosk_1_m:
                defb #C0,#00,#00,#00,#00,#00,#C0,#00,#00,#00,#00,#00,#D0,#00,#00,#00
                defb #76,#DA,#C0,#00,#00,#00,#76,#DA,#C0,#00,#00,#00,#76,#DA,#C0,#00
                defb #00,#00,#76,#DA,#C8,#00,#00,#00,#76,#DA,#C0,#00,#00,#00,#76,#DA
                defb #07,#47,#47,#47,#06,#06
GFX_URBAN_WIDTH equ 6
GFX_URBAN_LINES equ 8
GFX_URBAN_COUNT equ 12
gfx_forest_table:
                defw gfx_forest_ground_a
                defw gfx_forest_ground_a_m
                defw gfx_forest_ground_b
                defw gfx_forest_ground_b_m
                defw gfx_forest_path
                defw gfx_forest_path_m
                defw gfx_forest_fence
                defw gfx_forest_fence_m
                defw gfx_forest_trans_urban_forest_0
                defw gfx_forest_trans_urban_forest_0_m
                defw gfx_forest_trans_urban_forest_1
                defw gfx_forest_trans_urban_forest_1_m
                defw gfx_forest_trans_forest_urban_0
                defw gfx_forest_trans_forest_urban_0_m
                defw gfx_forest_trans_forest_urban_1
                defw gfx_forest_trans_forest_urban_1_m
IDX_FOREST_GROUND_A equ 0
gfx_forest_ground_a:
                defb #08,#02,#80,#10,#14,#01,#04,#01,#44,#08,#0A,#01,#00,#00,#02,#00
                defb #00,#01,#02,#00,#00,#00,#08,#01,#09,#00,#00,#80,#04,#01,#04,#01
                defb #00,#60,#00,#01,#08,#00,#80,#10,#00,#01,#04,#00,#00,#00,#00,#01
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_GROUND_A_M equ 1
gfx_forest_ground_a_m:
                defb #80,#28,#08,#01,#40,#10,#80,#50,#10,#22,#80,#20,#80,#00,#00,#40
                defb #00,#00,#80,#10,#00,#00,#00,#40,#80,#20,#01,#00,#00,#90,#80,#00
                defb #06,#00,#80,#20,#80,#00,#08,#01,#00,#10,#80,#00,#00,#00,#00,#20
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_GROUND_B equ 2
gfx_forest_ground_b:
                defb #10,#00,#00,#20,#00,#01,#08,#40,#00,#50,#C4,#01,#00,#21,#00,#20
                defb #62,#01,#20,#00,#80,#40,#80,#01,#10,#00,#00,#20,#40,#01,#20,#04
                defb #00,#20,#00,#01,#10,#02,#00,#10,#00,#01,#00,#00,#00,#00,#00,#01
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_GROUND_B_M equ 3
gfx_forest_ground_b_m:
                defb #80,#00,#04,#00,#00,#08,#80,#23,#0A,#00,#02,#10,#80,#46,#04,#00
                defb #84,#00,#80,#01,#02,#01,#00,#04,#80,#02,#04,#00,#00,#08,#80,#00
                defb #04,#00,#20,#04,#80,#00,#08,#00,#40,#08,#80,#00,#00,#00,#00,#00
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_PATH equ 4
gfx_forest_path:
                defb #00,#00,#00,#00,#00,#01,#00,#00,#00,#00,#00,#01,#00,#00,#00,#00
                defb #00,#01,#02,#04,#08,#10,#20,#01,#00,#00,#00,#00,#00,#01,#00,#00
                defb #00,#00,#00,#01,#00,#00,#00,#00,#00,#01,#00,#00,#00,#00,#00,#01
                defb #30,#30,#30,#30,#30,#30
IDX_FOREST_PATH_M equ 5
gfx_forest_path_m:
                defb #80,#00,#00,#00,#00,#00,#80,#00,#00,#00,#00,#00,#80,#00,#00,#00
                defb #00,#00,#80,#04,#08,#10,#20,#40,#80,#00,#00,#00,#00,#00,#80,#00
                defb #00,#00,#00,#00,#80,#00,#00,#00,#00,#00,#80,#00,#00,#00,#00,#00
                defb #30,#30,#30,#30,#30,#30
IDX_FOREST_FENCE equ 6
gfx_forest_fence:
                defb #00,#00,#00,#00,#00,#01,#18,#18,#18,#18,#18,#19,#FF,#FF,#FF,#FF
                defb #FF,#FF,#18,#18,#18,#18,#18,#19,#18,#18,#18,#18,#18,#19,#FF,#FF
                defb #FF,#FF,#FF,#FF,#18,#18,#18,#18,#18,#19,#00,#00,#00,#00,#00,#01
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_FENCE_M equ 7
gfx_forest_fence_m:
                defb #80,#00,#00,#00,#00,#00,#98,#18,#18,#18,#18,#18,#FF,#FF,#FF,#FF
                defb #FF,#FF,#98,#18,#18,#18,#18,#18,#98,#18,#18,#18,#18,#18,#FF,#FF
                defb #FF,#FF,#FF,#FF,#98,#18,#18,#18,#18,#18,#80,#00,#00,#00,#00,#00
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_TRANS_URBAN_FOREST_0 equ 8
gfx_forest_trans_urban_forest_0:
                defb #00,#00,#00,#00,#00,#00,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01
                defb #00,#0B,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01,#00,#03,#00,#01
                defb #00,#01,#00,#03,#00,#01,#00,#01,#00,#13,#00,#00,#00,#00,#00,#03
                defb #47,#07,#47,#07,#47,#07
IDX_FOREST_TRANS_URBAN_FOREST_0_M equ 9
gfx_forest_trans_urban_forest_0_m:
                defb #00,#00,#00,#00,#00,#00,#C0,#00,#80,#00,#80,#00,#D0,#00,#80,#00
                defb #80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00
                defb #80,#00,#80,#00,#C8,#00,#80,#00,#80,#00,#C0,#00,#00,#00,#00,#00
                defb #07,#47,#07,#47,#07,#47
IDX_FOREST_TRANS_URBAN_FOREST_1 equ 10
gfx_forest_trans_urban_forest_1:
                defb #08,#02,#80,#10,#14,#01,#04,#01,#44,#08,#0A,#01,#00,#00,#02,#00
                defb #00,#01,#02,#00,#00,#00,#08,#01,#09,#00,#00,#80,#04,#01,#04,#01
                defb #00,#60,#00,#01,#08,#00,#80,#10,#00,#01,#FF,#FF,#FF,#FF,#FF,#FF
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_TRANS_URBAN_FOREST_1_M equ 11
gfx_forest_trans_urban_forest_1_m:
                defb #80,#28,#08,#01,#40,#10,#80,#50,#10,#22,#80,#20,#80,#00,#00,#40
                defb #00,#00,#80,#10,#00,#00,#00,#40,#80,#20,#01,#00,#00,#90,#80,#00
                defb #06,#00,#80,#20,#80,#00,#08,#01,#00,#10,#FF,#FF,#FF,#FF,#FF,#FF
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_TRANS_FOREST_URBAN_0 equ 12
gfx_forest_trans_forest_urban_0:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#04,#01,#44,#08,#0A,#01,#00,#00,#02,#00
                defb #00,#01,#02,#00,#00,#00,#08,#01,#09,#00,#00,#80,#04,#01,#04,#01
                defb #00,#60,#00,#01,#08,#00,#80,#10,#00,#01,#04,#00,#00,#00,#00,#01
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_TRANS_FOREST_URBAN_0_M equ 13
gfx_forest_trans_forest_urban_0_m:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#80,#50,#10,#22,#80,#20,#80,#00,#00,#40
                defb #00,#00,#80,#10,#00,#00,#00,#40,#80,#20,#01,#00,#00,#90,#80,#00
                defb #06,#00,#80,#20,#80,#00,#08,#01,#00,#10,#80,#00,#00,#00,#00,#20
                defb #20,#20,#20,#20,#20,#20
IDX_FOREST_TRANS_FOREST_URBAN_1 equ 14
gfx_forest_trans_forest_urban_1:
                defb #00,#00,#00,#00,#00,#03,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01
                defb #00,#0B,#00,#01,#00,#01,#00,#03,#00,#01,#00,#01,#00,#03,#00,#01
                defb #00,#01,#00,#03,#00,#01,#00,#01,#00,#13,#00,#00,#00,#00,#00,#00
                defb #47,#07,#47,#07,#47,#07
IDX_FOREST_TRANS_FOREST_URBAN_1_M equ 15
gfx_forest_trans_forest_urban_1_m:
                defb #C0,#00,#00,#00,#00,#00,#C0,#00,#80,#00,#80,#00,#D0,#00,#80,#00
                defb #80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00,#80,#00,#80,#00,#C0,#00
                defb #80,#00,#80,#00,#C8,#00,#80,#00,#80,#00,#00,#00,#00,#00,#00,#00
                defb #07,#47,#07,#47,#07,#47
GFX_FOREST_WIDTH equ 6
GFX_FOREST_LINES equ 8
GFX_FOREST_COUNT equ 16
gfx_bridges_table:
                defw gfx_bridges_footbridge_0
                defw gfx_bridges_footbridge_1
                defw gfx_bridges_footbridge_2
                defw gfx_bridges_footbridge_shadow
                defw gfx_bridges_roadbridge_0
                defw gfx_bridges_roadbridge_1
                defw gfx_bridges_roadbridge_2
                defw gfx_bridges_roadbridge_3
                defw gfx_bridges_roadbridge_4
                defw gfx_bridges_roadbridge_5
                defw gfx_bridges_roadbridge_shadow
IDX_BRIDGES_FOOTBRIDGE_0 equ 0
gfx_bridges_footbridge_0:
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20
                defb #82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82
                defb #08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08
                defb #20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20
                defb #82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82
                defb #08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
                defb #10,#10,#10,#10,#10,#10,#10,#10
IDX_BRIDGES_FOOTBRIDGE_1 equ 1
gfx_bridges_footbridge_1:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#80,#08,#00,#80,#08,#00,#80,#08
                defb #00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00
                defb #80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80
                defb #08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08
                defb #00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00
                defb #80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80
                defb #08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08
                defb #00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00
                defb #80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80,#08,#00,#80
                defb #08,#00,#80,#08,#00,#80,#08,#00,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38
                defb #38,#38,#38,#38,#38,#38,#38,#38
IDX_BRIDGES_FOOTBRIDGE_2 equ 2
gfx_bridges_footbridge_2:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20
                defb #82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82
                defb #08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08
                defb #20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20
                defb #82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82
                defb #08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08,#20,#82,#08
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10,#10
                defb #10,#10,#10,#10,#10,#10,#10,#10
IDX_BRIDGES_FOOTBRIDGE_SHADOW equ 3
gfx_bridges_footbridge_shadow:
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#55,#55,#55,#55,#55,#55,#55,#55
                defb #55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01
                defb #01,#01,#01,#01,#01,#01,#01,#01
IDX_BRIDGES_ROADBRIDGE_0 equ 4
gfx_bridges_roadbridge_0:
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38
                defb #38,#38,#38,#38,#38,#38,#38,#38
IDX_BRIDGES_ROADBRIDGE_1 equ 5
gfx_bridges_roadbridge_1:
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47
                defb #47,#47,#47,#47,#47,#47,#47,#47
IDX_BRIDGES_ROADBRIDGE_2 equ 6
gfx_bridges_roadbridge_2:
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47
                defb #47,#47,#47,#47,#47,#47,#47,#47
IDX_BRIDGES_ROADBRIDGE_3 equ 7
gfx_bridges_roadbridge_3:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47
                defb #47,#47,#47,#47,#47,#47,#47,#47
IDX_BRIDGES_ROADBRIDGE_4 equ 8
gfx_bridges_roadbridge_4:
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47,#47
                defb #47,#47,#47,#47,#47,#47,#47,#47
IDX_BRIDGES_ROADBRIDGE_5 equ 9
gfx_bridges_roadbridge_5:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10,#08,#10
                defb #08,#10,#08,#10,#08,#10,#08,#10,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0,#0F,#F0
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38,#38
                defb #38,#38,#38,#38,#38,#38,#38,#38
IDX_BRIDGES_ROADBRIDGE_SHADOW equ 10
gfx_bridges_roadbridge_shadow:
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#55,#55,#55,#55,#55,#55,#55,#55
                defb #55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55,#55
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA
                defb #AA,#AA,#AA,#AA,#AA,#AA,#AA,#AA,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00,#00
                defb #01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01,#01
                defb #01,#01,#01,#01,#01,#01,#01,#01
GFX_BRIDGES_WIDTH equ 24
GFX_BRIDGES_LINES equ 8
GFX_BRIDGES_COUNT equ 11
gfx_platform_table:
                defw gfx_platform_end_lo
                defw gfx_platform_end_lo_m
                defw gfx_platform_end_hi
                defw gfx_platform_end_hi_m
                defw gfx_platform_plain
                defw gfx_platform_plain_m
                defw gfx_platform_bench
                defw gfx_platform_bench_m
                defw gfx_platform_sign
                defw gfx_platform_sign_m
                defw gfx_platform_roof
                defw gfx_platform_roof_m
                defw gfx_platform_roof_lo
                defw gfx_platform_roof_lo_m
IDX_PLATFORM_END_LO equ 0
gfx_platform_end_lo:
                defb #00,#00,#05,#00,#00,#05,#00,#00,#05,#00,#00,#05,#92,#49,#25,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#38,#38,#38
IDX_PLATFORM_END_LO_M equ 1
gfx_platform_end_lo_m:
                defb #A0,#00,#00,#A0,#00,#00,#A0,#00,#00,#A0,#00,#00,#A4,#92,#49,#FF
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#38,#38,#38
IDX_PLATFORM_END_HI equ 2
gfx_platform_end_hi:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#92,#49,#25,#00,#00,#05,#00
                defb #00,#05,#00,#00,#05,#00,#00,#05,#38,#38,#38
IDX_PLATFORM_END_HI_M equ 3
gfx_platform_end_hi_m:
                defb #FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#FF,#A4,#92,#49,#A0,#00,#00,#A0
                defb #00,#00,#A0,#00,#00,#A0,#00,#00,#38,#38,#38
IDX_PLATFORM_PLAIN equ 4
gfx_platform_plain:
                defb #00,#00,#05,#00,#00,#05,#00,#00,#05,#00,#00,#05,#7F,#FF,#FD,#00
                defb #00,#05,#00,#00,#05,#00,#00,#05,#38,#38,#38
IDX_PLATFORM_PLAIN_M equ 5
gfx_platform_plain_m:
                defb #A0,#00,#00,#A0,#00,#00,#A0,#00,#00,#A0,#00,#00,#BF,#FF,#FE,#A0
                defb #00,#00,#A0,#00,#00,#A0,#00,#00,#38,#38,#38
IDX_PLATFORM_BENCH equ 6
gfx_platform_bench:
                defb #00,#00,#05,#00,#00,#05,#0F,#FF,#05,#0F,#FF,#05,#04,#02,#05,#0F
                defb #FF,#05,#00,#00,#05,#00,#00,#05,#38,#38,#38
IDX_PLATFORM_BENCH_M equ 7
gfx_platform_bench_m:
                defb #A0,#00,#00,#A0,#00,#00,#A0,#FF,#F0,#A0,#FF,#F0,#A0,#40,#20,#A0
                defb #FF,#F0,#A0,#00,#00,#A0,#00,#00,#38,#38,#38
IDX_PLATFORM_SIGN equ 8
gfx_platform_sign:
                defb #00,#00,#05,#00,#00,#FD,#00,#00,#FD,#36,#D8,#FD,#36,#D8,#FD,#00
                defb #00,#FD,#00,#00,#FD,#00,#00,#05,#4F,#4F,#10
IDX_PLATFORM_SIGN_M equ 9
gfx_platform_sign_m:
                defb #A0,#00,#00,#BF,#00,#00,#BF,#00,#00,#BF,#1B,#6C,#BF,#1B,#6C,#BF
                defb #00,#00,#BF,#00,#00,#A0,#00,#00,#10,#4F,#4F
IDX_PLATFORM_ROOF equ 10
gfx_platform_roof:
                defb #00,#00,#05,#FF,#FF,#FD,#00,#00,#05,#FF,#FF,#FD,#00,#00,#05,#FF
                defb #FF,#FD,#00,#00,#05,#FF,#FF,#FD,#10,#10,#10
IDX_PLATFORM_ROOF_M equ 11
gfx_platform_roof_m:
                defb #A0,#00,#00,#BF,#FF,#FF,#A0,#00,#00,#BF,#FF,#FF,#A0,#00,#00,#BF
                defb #FF,#FF,#A0,#00,#00,#BF,#FF,#FF,#10,#10,#10
IDX_PLATFORM_ROOF_LO equ 12
gfx_platform_roof_lo:
                defb #00,#00,#05,#FF,#FF,#FD,#00,#00,#05,#FF,#FF,#FD,#00,#00,#05,#FF
                defb #FF,#FD,#00,#00,#05,#FF,#FF,#FD,#10,#10,#10
IDX_PLATFORM_ROOF_LO_M equ 13
gfx_platform_roof_lo_m:
                defb #A0,#00,#00,#BF,#FF,#FF,#A0,#00,#00,#BF,#FF,#FF,#A0,#00,#00,#BF
                defb #FF,#FF,#A0,#00,#00,#BF,#FF,#FF,#10,#10,#10
GFX_PLATFORM_WIDTH equ 3
GFX_PLATFORM_LINES equ 8
GFX_PLATFORM_COUNT equ 14
GFX_PLATFORM_SEQ_LEN equ 23
gfx_platform_seq:
                defb #FF,#01,#02,#03,#02,#02,#03,#02,#05,#04,#05,#05,#04,#05,#06,#02
                defb #03,#02,#00,#FF,#FF,#FF,#FF
gfx_urban_ov_table:
                defw gfx_urban_ov_car_red
                defw gfx_urban_ov_car_red_m
                defw gfx_urban_ov_car_blue
                defw gfx_urban_ov_car_blue_m
                defw gfx_urban_ov_car_white
                defw gfx_urban_ov_car_white_m
                defw gfx_urban_ov_taxi
                defw gfx_urban_ov_taxi_m
                defw gfx_urban_ov_bus
                defw gfx_urban_ov_bus_m
                defw gfx_urban_ov_trolley
                defw gfx_urban_ov_trolley_m
                defw 51
IDX_URBAN_OV_CAR_RED equ 0
gfx_urban_ov_car_red:
                defb #02,#10,#42,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_CAR_RED_M equ 1
gfx_urban_ov_car_red_m:
                defb #02,#10,#42,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_CAR_BLUE equ 2
gfx_urban_ov_car_blue:
                defb #02,#10,#41,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_CAR_BLUE_M equ 3
gfx_urban_ov_car_blue_m:
                defb #02,#10,#41,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_CAR_WHITE equ 4
gfx_urban_ov_car_white:
                defb #02,#10,#47,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#3C,#00,#02,#80,#3F,#01,#3C,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_CAR_WHITE_M equ 5
gfx_urban_ov_car_white_m:
                defb #02,#10,#47,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3C,#01,#FC,#00,#02,#80,#3C,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_TAXI equ 6
gfx_urban_ov_taxi:
                defb #02,#10,#46,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3E,#01
                defb #7C,#00,#02,#80,#3C,#01,#3C,#00,#02,#80,#3E,#01,#7C,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 51
IDX_URBAN_OV_TAXI_M equ 7
gfx_urban_ov_taxi_m:
                defb #02,#10,#46,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3E,#01
                defb #7C,#00,#02,#80,#3C,#01,#3C,#00,#02,#80,#3E,#01,#7C,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8
                defw 147
                defw 99
                defw 51
IDX_URBAN_OV_BUS equ 8
gfx_urban_ov_bus:
                defb #02,#20,#45,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80
                defb #3F,#01,#FC
                defw 147
                defw 99
                defw 51
IDX_URBAN_OV_BUS_M equ 9
gfx_urban_ov_bus_m:
                defb #02,#20,#45,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80
                defb #3F,#01,#FC
                defw 147
                defw 99
                defw 51
IDX_URBAN_OV_TROLLEY equ 10
gfx_urban_ov_trolley:
                defb #02,#20,#46,#00,#02,#F1,#04,#8F,#20,#00,#02,#F1,#04,#8F,#20,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01
                defb #0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3C,#01,#FC,#00
                defb #02,#80,#3C,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3C,#01,#FC,#00,#02,#80,#3C,#01
                defb #FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80
                defb #3F,#01,#FC
                defw 147
                defw 99
                defw 51
IDX_URBAN_OV_TROLLEY_M equ 11
gfx_urban_ov_trolley_m:
                defb #02,#20,#46,#00,#02,#F1,#04,#8F,#20,#00,#02,#F1,#04,#8F,#20,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01
                defb #0C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#3C,#00
                defb #02,#80,#3F,#01,#3C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01
                defb #FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#01,#3C,#00,#02,#80,#3F,#01
                defb #3C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#3F,#01,#FC,#00
                defb #02,#80,#3F,#01,#FC,#00,#02,#80,#30,#01,#0C,#00,#02,#80,#37,#01
                defb #EC,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#2F,#01,#F4,#00,#02,#80
                defb #3F,#01,#FC
gfx_forest_ov_table:
                defw gfx_forest_ov_pine
                defw gfx_forest_ov_oak
                defw gfx_forest_ov_cypress
                defw gfx_forest_ov_bush
                defw gfx_forest_ov_rock
                defw 119
                defw 55
IDX_FOREST_OV_PINE equ 0
gfx_forest_ov_pine:
                defb #03,#18,#00,#01,#01,#C3,#18,#01,#01,#81,#3C,#01,#01,#00,#6E,#00
                defb #03,#FE,#00,#00,#FB,#7F,#00,#00,#03,#FC,#01,#00,#BF,#3F,#80,#00
                defb #03,#F8,#03,#00,#F7,#1F,#C0,#00,#03,#FC,#01,#00,#FE,#3F,#80,#00
                defb #03,#F8,#03,#00,#7F,#1F,#C0,#00,#03,#F0,#07,#00,#EF,#0F,#E0,#00
                defb #03,#E0,#0F,#00,#7E,#07,#F0,#00,#03,#F0,#07,#00,#FF,#0F,#E0,#00
                defb #03,#E0,#0E,#00,#FB,#03,#F8,#00,#03,#C0,#1F,#00,#FF,#01,#BC,#00
                defb #03,#80,#3D,#00,#F7,#00,#FE,#00,#03,#C0,#1F,#00,#FF,#01,#FC,#00
                defb #03,#80,#3F,#00,#DF,#00,#BE,#00,#03,#00,#77,#00,#FF,#00,#FF,#00
                defb #03,#80,#3F,#00,#FF,#00,#FE,#00,#03,#E0,#0F,#00,#FF,#03,#F8,#00
                defb #03,#FC,#01,#00,#FF,#1F,#C0,#01,#01,#81,#3C,#01,#01,#81,#24,#01
                defb #01,#81,#24,#01,#01,#C3,#18
                defw 159
                defw 79
IDX_FOREST_OV_OAK equ 1
gfx_forest_ov_oak:
                defb #04,#18,#00,#01,#02,#00,#7F,#03,#F8,#00,#04,#F8,#03,#00,#FF,#00
                defb #FF,#7F,#00,#00,#04,#E0,#0F,#00,#DF,#00,#EF,#1F,#C0,#00,#04,#C0
                defb #1E,#00,#FF,#00,#7F,#0F,#E0,#00,#04,#80,#3F,#00,#FB,#00,#FD,#07
                defb #F0,#00,#04,#00,#77,#00,#FF,#00,#FF,#03,#F8,#00,#04,#00,#7F,#00
                defb #DF,#00,#EF,#01,#FC,#00,#04,#00,#FF,#00,#FF,#00,#FF,#01,#BC,#00
                defb #04,#00,#FB,#00,#FE,#00,#FF,#00,#FE,#00,#04,#00,#FF,#00,#FF,#00
                defb #FD,#00,#FE,#00,#04,#00,#7F,#00,#EF,#00,#FF,#00,#FE,#00,#04,#00
                defb #77,#00,#FF,#00,#EF,#00,#FE,#00,#04,#00,#FF,#00,#FF,#00,#FF,#00
                defb #EF,#00,#04,#00,#FF,#00,#BF,#00,#FF,#00,#FF,#00,#04,#00,#7F,#00
                defb #FF,#00,#BF,#00,#FE,#00,#04,#00,#7B,#00,#FF,#00,#FF,#00,#DE,#00
                defb #04,#80,#3F,#00,#FF,#00,#FF,#01,#FC,#00,#04,#C0,#1F,#00,#F7,#00
                defb #FD,#03,#F8,#00,#04,#E0,#0F,#00,#FF,#00,#FF,#07,#F0,#00,#04,#F8
                defb #03,#00,#FF,#00,#FF,#1F,#C0,#01,#02,#00,#7F,#00,#FE,#01,#02,#F0
                defb #07,#0F,#E0,#01,#02,#F0,#04,#0F,#20,#01,#02,#F8,#03,#1F,#C0
                defw 99
                defw 51
IDX_FOREST_OV_CYPRESS equ 2
gfx_forest_ov_cypress:
                defb #02,#18,#00,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#06,#0F,#E0,#00,#02,#E0,#0F,#07,#B0,#00,#02,#E0,#0D,#07
                defb #F0,#00,#02,#E0,#0F,#07,#F0,#00,#02,#E0,#0F,#07,#70,#00,#02,#E0
                defb #0B,#07,#F0,#00,#02,#E0,#0F,#07,#D0,#00,#02,#E0,#0E,#07,#F0,#00
                defb #02,#E0,#0F,#07,#F0,#00,#02,#E0,#0F,#07,#B0,#00,#02,#E0,#0B,#07
                defb #F0,#00,#02,#E0,#0F,#07,#F0,#00,#02,#E0,#0E,#07,#F0,#00,#02,#E0
                defb #0F,#07,#F0,#00,#02,#F0,#07,#0F,#E0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#FC,#01,#3F,#80,#00,#00,#00,#00
IDX_FOREST_OV_BUSH equ 3
gfx_forest_ov_bush:
                defb #02,#08,#00,#00,#00,#00,#02,#E0,#0F,#0F,#E0,#00,#02,#80,#3B,#03
                defb #F8,#00,#02,#00,#7F,#01,#7C,#00,#02,#00,#6F,#01,#FC,#00,#02,#80
                defb #3F,#03,#78,#00,#02,#E0,#0F,#0F,#E0,#00,#00
IDX_FOREST_OV_ROCK equ 4
gfx_forest_ov_rock:
                defb #02,#08,#07,#00,#00,#00,#02,#F0,#07,#1F,#C0,#00,#02,#C0,#1F,#07
                defb #F0,#00,#02,#80,#3E,#03,#F8,#00,#02,#80,#3F,#01,#CC,#00,#02,#C0
                defb #1F,#03,#F8,#00,#02,#F0,#07,#0F,#E0,#00,#00
gfx_items_table:
                defw gfx_items_coin0
                defw gfx_items_coin1
                defw gfx_items_coin2
                defw gfx_items_coin3
                defw gfx_items_pu_magnet
                defw gfx_items_pu_turbo
                defw gfx_items_pu_slow
                defw gfx_items_pu_spring
                defw gfx_items_pu_helmet
                defw gfx_items_pu_ticket
IDX_ITEMS_COIN0 equ 0
gfx_items_coin0:
                defb #02,#08,#46,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#38,#01,#1C,#00
                defb #02,#80,#37,#01,#EC,#00,#02,#80,#36,#01,#6C,#00,#02,#80,#36,#01
                defb #6C,#00,#02,#80,#37,#01,#EC,#00,#02,#80,#38,#01,#1C,#00,#02,#C0
                defb #1F,#03,#F8
IDX_ITEMS_COIN1 equ 1
gfx_items_coin1:
                defb #02,#08,#46,#00,#02,#F0,#07,#0F,#E0,#00,#02,#E0,#0C,#07,#30,#00
                defb #02,#E0,#0B,#07,#D0,#00,#02,#E0,#0A,#07,#50,#00,#02,#E0,#0A,#07
                defb #50,#00,#02,#E0,#0B,#07,#D0,#00,#02,#E0,#0C,#07,#30,#00,#02,#F0
                defb #07,#0F,#E0
IDX_ITEMS_COIN2 equ 2
gfx_items_coin2:
                defb #02,#08,#46,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F,#80,#00
                defb #02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC
                defb #01,#3F,#80
IDX_ITEMS_COIN3 equ 3
gfx_items_coin3:
                defb #02,#08,#46,#00,#02,#F0,#07,#0F,#E0,#00,#02,#E0,#0C,#07,#30,#00
                defb #02,#E0,#0B,#07,#D0,#00,#02,#E0,#0B,#07,#50,#00,#02,#E0,#0B,#07
                defb #50,#00,#02,#E0,#0B,#07,#D0,#00,#02,#E0,#0C,#07,#30,#00,#02,#F0
                defb #07,#0F,#E0
                defw 51
IDX_ITEMS_PU_MAGNET equ 4
gfx_items_pu_magnet:
                defb #02,#0C,#42,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#6E,#00,#76,#00,#02,#00,#6E,#00,#76,#00,#02,#00,#6C,#00
                defb #36,#00,#02,#00,#6C,#00,#36,#00,#02,#00,#6C,#00,#36,#00,#02,#00
                defb #6C,#00,#36,#00,#02,#00,#68,#00,#16,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
                defw 51
IDX_ITEMS_PU_TURBO equ 5
gfx_items_pu_turbo:
                defb #02,#0C,#46,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#63,#00,#06,#00,#02,#00,#61,#00,#86,#00,#02,#00,#60,#00
                defb #C6,#00,#02,#00,#60,#00,#66,#00,#02,#00,#60,#00,#C6,#00,#02,#00
                defb #61,#00,#86,#00,#02,#00,#63,#00,#06,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
                defw 51
IDX_ITEMS_PU_SLOW equ 6
gfx_items_pu_slow:
                defb #02,#0C,#44,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#60,#00,#06,#00,#02,#00,#67,#00,#CE,#00,#02,#00,#6D,#00
                defb #6A,#00,#02,#00,#6A,#00,#BA,#00,#02,#00,#6F,#00,#E6,#00,#02,#00
                defb #64,#00,#26,#00,#02,#00,#60,#00,#06,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
                defw 51
IDX_ITEMS_PU_SPRING equ 7
gfx_items_pu_spring:
                defb #02,#0C,#45,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#63,#00,#C6,#00,#02,#00,#60,#00,#46,#00,#02,#00,#63,#00
                defb #C6,#00,#02,#00,#62,#00,#06,#00,#02,#00,#63,#00,#C6,#00,#02,#00
                defb #60,#00,#46,#00,#02,#00,#63,#00,#C6,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
                defw 51
IDX_ITEMS_PU_HELMET equ 8
gfx_items_pu_helmet:
                defb #02,#0C,#47,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#60,#00,#06,#00,#02,#00,#63,#00,#C6,#00,#02,#00,#67,#00
                defb #E6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#7F,#00,#FE,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
                defw 51
IDX_ITEMS_PU_TICKET equ 9
gfx_items_pu_ticket:
                defb #02,#0C,#43,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#30,#01,#0C,#00
                defb #02,#00,#60,#00,#06,#00,#02,#00,#6F,#00,#F6,#00,#02,#00,#6A,#00
                defb #96,#00,#02,#00,#6D,#00,#B6,#00,#02,#00,#6A,#00,#96,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#60,#00,#06,#00,#02,#00,#60,#00,#06,#00
                defb #02,#80,#30,#01,#0C,#00,#02,#C0,#1F,#03,#F8
gfx_player_table:
                defw gfx_player_s1_run0
                defw gfx_player_s1_run1
                defw gfx_player_s1_run2
                defw gfx_player_s1_run3
                defw gfx_player_s1_lean_l
                defw gfx_player_s1_lean_r
                defw gfx_player_s1_crash0
                defw gfx_player_s1_crash1
                defw gfx_player_s2_jump_up
                defw gfx_player_s2_jump_down
                defw gfx_player_s3_run0
                defw gfx_player_s3_run1
                defw gfx_player_s3_run2
                defw gfx_player_s3_run3
                defw gfx_player_s3_lean_l
                defw gfx_player_s3_lean_r
                defw gfx_player_s3_crash0
                defw gfx_player_s3_crash1
                defw gfx_player_s3_jump_up
                defw gfx_player_s3_jump_down
                defw gfx_player_s4_jump_up
                defw gfx_player_s4_jump_down
                defw gfx_player_s5_jump
IDX_PLAYER_S1_RUN0 equ 0
gfx_player_s1_run0:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #36,#01,#EC,#00,#02,#80,#37,#01,#6C,#00,#02,#80,#33,#01,#CC,#00
                defb #02,#F8,#03,#01,#CC,#00,#02,#FC,#00,#21,#0C,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#7F,#00,#00,#02,#F8
                defb #03,#7F,#00
IDX_PLAYER_S1_RUN1 equ 1
gfx_player_s1_run1:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #36,#01,#EC,#00,#02,#80,#37,#01,#6C,#00,#02,#80,#33,#01,#CC,#00
                defb #02,#80,#33,#01,#CC,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#00
IDX_PLAYER_S1_RUN2 equ 2
gfx_player_s1_run2:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #36,#01,#EC,#00,#02,#80,#37,#01,#6C,#00,#02,#80,#33,#01,#CC,#00
                defb #02,#80,#33,#1F,#C0,#00,#02,#84,#30,#3F,#00,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#01,#01,#0F,#60,#01,#01,#0F,#60
IDX_PLAYER_S1_RUN3 equ 3
gfx_player_s1_run3:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#02,#1F,#40,#00,#02,#FC,#01,#3F,#80,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#C0,#1F,#03,#F8,#00,#02,#80,#37,#01,#EC,#00,#02,#80
                defb #36,#01,#EC,#00,#02,#80,#37,#01,#6C,#00,#02,#80,#33,#01,#CC,#00
                defb #02,#80,#33,#01,#CC,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#00
IDX_PLAYER_S1_LEAN_L equ 4
gfx_player_s1_lean_l:
                defb #02,#10,#FF,#00,#01,#F0,#06,#00,#02,#E0,#0F,#7F,#00,#00,#02,#E0
                defb #09,#7F,#00,#00,#01,#F0,#06,#00,#02,#F8,#03,#7F,#00,#00,#02,#80
                defb #3F,#07,#F0,#00,#02,#00,#6F,#03,#D8,#00,#02,#00,#6D,#03,#D8,#00
                defb #02,#00,#6E,#03,#D8,#00,#02,#00,#67,#03,#98,#00,#02,#00,#67,#03
                defb #98,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8
                defb #03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60
IDX_PLAYER_S1_LEAN_R equ 5
gfx_player_s1_lean_r:
                defb #02,#10,#FF,#01,#01,#0F,#60,#00,#02,#FE,#00,#07,#F0,#00,#02,#FE
                defb #00,#07,#90,#01,#01,#0F,#60,#00,#02,#FE,#00,#1F,#C0,#00,#02,#E0
                defb #0F,#01,#FC,#00,#02,#C0,#1B,#00,#F6,#00,#02,#C0,#1B,#00,#76,#00
                defb #02,#C0,#1B,#00,#B6,#00,#02,#C0,#19,#00,#E6,#00,#02,#C0,#19,#00
                defb #E6,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8
                defb #03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60
IDX_PLAYER_S1_CRASH0 equ 6
gfx_player_s1_crash0:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#33,#1F,#C0,#00
                defb #02,#80,#32,#1F,#40,#00,#02,#84,#31,#21,#8C,#00,#02,#84,#31,#21
                defb #8C,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0,#1F,#01,#FC,#00,#02,#F0
                defb #06,#01,#EC,#00,#02,#F0,#07,#0F,#60,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F0,#06,#87,#30,#00,#02,#F0
                defb #06,#87,#30
IDX_PLAYER_S1_CRASH1 equ 7
gfx_player_s1_crash1:
                defb #02,#10,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#01,#CC,#00
                defb #02,#F8,#02,#01,#4C,#00,#02,#84,#31,#21,#8C,#00,#02,#84,#31,#21
                defb #8C,#00,#02,#80,#3F,#01,#FC,#00,#02,#80,#3F,#03,#F8,#00,#02,#80
                defb #36,#0F,#E0,#00,#02,#F0,#07,#0F,#60,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#FC,#00,#3F,#00,#00,#02,#F8,#03,#0F
                defb #60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F0,#06,#87,#30,#00,#02,#F0
                defb #06,#87,#30
IDX_PLAYER_S2_JUMP_UP equ 8
gfx_player_s2_jump_up:
                defb #02,#12,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#33,#01,#CC,#00
                defb #02,#80,#33,#01,#CC,#00,#02,#80,#32,#01,#4C,#00,#02,#84,#31,#21
                defb #8C,#00,#02,#84,#31,#21,#8C,#00,#02,#80,#3F,#01,#FC,#00,#02,#C0
                defb #1F,#03,#F8,#00,#02,#F0,#06,#0F,#E0,#00,#02,#F0,#07,#0F,#60,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#F8,#03,#1F,#C0,#00,#02,#FC,#00,#3F
                defb #00,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8
                defb #03,#0F,#60,#00,#00,#00,#00
IDX_PLAYER_S2_JUMP_DOWN equ 9
gfx_player_s2_jump_down:
                defb #02,#12,#FF,#00,#02,#FC,#01,#3F,#80,#00,#02,#F8,#03,#1F,#C0,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#F8,#02,#1F,#40,#00,#02,#FC,#01,#3F
                defb #80,#00,#02,#FC,#01,#3F,#80,#00,#02,#C0,#1F,#03,#F8,#00,#02,#00
                defb #7F,#00,#FE,#00,#02,#00,#E6,#00,#E7,#00,#02,#30,#87,#0C,#61,#00
                defb #02,#F8,#03,#1F,#C0,#00,#02,#F8,#03,#1F,#C0,#00,#02,#FC,#00,#3F
                defb #00,#00,#02,#F8,#03,#0F,#60,#00,#02,#F8,#03,#0F,#60,#00,#02,#F0
                defb #06,#87,#30,#00,#02,#F0,#06,#87,#30,#00,#02,#E1,#0C,#C3,#18
IDX_PLAYER_S3_RUN0 equ 10
gfx_player_s3_run0:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#07,#0F,#E0,#00,#02,#F0,#06,#0F,#60,#00,#02,#F8,#03,#1F
                defb #C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#3F,#01,#FC,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00,#6F,#00,#76,#00
                defb #02,#00,#6F,#00,#F6,#00,#02,#00,#67,#00,#E6,#00,#02,#F0,#07,#00
                defb #E6,#00,#02,#F8,#00,#10,#06,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #02,#F0,#07,#7F,#00,#00,#02,#F0,#07,#7F,#00
IDX_PLAYER_S3_RUN1 equ 11
gfx_player_s3_run1:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#07,#0F,#E0,#00,#02,#F0,#06,#0F,#60,#00,#02,#F8,#03,#1F
                defb #C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#3F,#01,#FC,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00,#6F,#00,#76,#00
                defb #02,#00,#6F,#00,#F6,#00,#02,#00,#67,#00,#E6,#00,#02,#00,#67,#00
                defb #E6,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #02,#F0,#07,#07,#70,#00,#00
IDX_PLAYER_S3_RUN2 equ 12
gfx_player_s3_run2:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#07,#0F,#E0,#00,#02,#F0,#06,#0F,#60,#00,#02,#F8,#03,#1F
                defb #C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#3F,#01,#FC,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00,#6F,#00,#76,#00
                defb #02,#00,#6F,#00,#F6,#00,#02,#00,#67,#00,#E6,#00,#02,#00,#67,#0F
                defb #E0,#00,#02,#08,#60,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#01
                defb #01,#07,#70,#01,#01,#07,#70
IDX_PLAYER_S3_RUN3 equ 13
gfx_player_s3_run3:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#07,#0F,#E0,#00,#02,#F0,#06,#0F,#60,#00,#02,#F8,#03,#1F
                defb #C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#3F,#01,#FC,#00,#02,#00
                defb #6F,#00,#F6,#00,#02,#00,#6E,#00,#F6,#00,#02,#00,#6F,#00,#76,#00
                defb #02,#00,#6F,#00,#F6,#00,#02,#00,#67,#00,#E6,#00,#02,#00,#67,#00
                defb #E6,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #02,#F0,#07,#07,#70,#00,#00
IDX_PLAYER_S3_LEAN_L equ 14
gfx_player_s3_lean_l:
                defb #02,#14,#FF,#00,#02,#E0,#0F,#7F,#00,#00,#02,#C0,#1F,#3F,#80,#00
                defb #02,#C0,#1F,#3F,#80,#00,#02,#C0,#19,#3F,#80,#00,#02,#E0,#0F,#7F
                defb #00,#00,#02,#F8,#03,#7F,#00,#00,#02,#00,#7F,#03,#F8,#00,#02,#00
                defb #DF,#01,#EC,#00,#02,#00,#DD,#01,#EC,#00,#02,#00,#DE,#01,#EC,#00
                defb #02,#00,#DF,#01,#EC,#00,#02,#00,#CF,#01,#CC,#00,#02,#00,#CF,#01
                defb #CC,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70
IDX_PLAYER_S3_LEAN_R equ 15
gfx_player_s3_lean_r:
                defb #02,#14,#FF,#00,#02,#FE,#00,#07,#F0,#00,#02,#FC,#01,#03,#F8,#00
                defb #02,#FC,#01,#03,#F8,#00,#02,#FC,#01,#03,#98,#00,#02,#FE,#00,#07
                defb #F0,#00,#02,#FE,#00,#1F,#C0,#00,#02,#C0,#1F,#00,#FE,#00,#02,#80
                defb #37,#00,#FB,#00,#02,#80,#37,#00,#7B,#00,#02,#80,#37,#00,#BB,#00
                defb #02,#80,#37,#00,#FB,#00,#02,#80,#33,#00,#F3,#00,#02,#80,#33,#00
                defb #F3,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70
IDX_PLAYER_S3_CRASH0 equ 16
gfx_player_s3_crash0:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#00,#67,#0F,#E0,#00
                defb #02,#00,#67,#0F,#E0,#00,#02,#00,#66,#00,#66,#00,#02,#08,#63,#10
                defb #C6,#00,#02,#0C,#61,#30,#86,#00,#02,#00,#7F,#00,#FE,#00,#02,#80
                defb #3F,#00,#FE,#00,#02,#E0,#0E,#00,#F6,#00,#02,#E0,#0F,#07,#70,#00
                defb #02,#E0,#0F,#07,#F0,#00,#02,#F0,#07,#0F,#E0,#00,#02,#F0,#07,#0F
                defb #E0,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#E0,#0E,#83,#38,#00,#02,#E0,#0E,#83,#38,#00
                defb #02,#C1,#1C,#C1,#1C,#00,#02,#C1,#1C,#C1,#1C
IDX_PLAYER_S3_CRASH1 equ 17
gfx_player_s3_crash1:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#00,#E6,#00
                defb #02,#F0,#07,#00,#E6,#00,#02,#00,#66,#00,#66,#00,#02,#08,#63,#10
                defb #C6,#00,#02,#0C,#61,#30,#86,#00,#02,#00,#7F,#00,#FE,#00,#02,#00
                defb #7F,#01,#FC,#00,#02,#00,#6E,#07,#F0,#00,#02,#E0,#0F,#07,#70,#00
                defb #02,#E0,#0F,#07,#F0,#00,#02,#F0,#07,#0F,#E0,#00,#02,#F0,#07,#0F
                defb #E0,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#E0,#0E,#83,#38,#00,#02,#E0,#0E,#83,#38,#00
                defb #02,#C1,#1C,#C1,#1C,#00,#02,#C1,#1C,#C1,#1C
IDX_PLAYER_S3_JUMP_UP equ 18
gfx_player_s3_jump_up:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#00,#67,#00,#E6,#00
                defb #02,#00,#67,#00,#E6,#00,#02,#00,#66,#00,#66,#00,#02,#08,#63,#10
                defb #C6,#00,#02,#0C,#61,#30,#86,#00,#02,#00,#7F,#00,#FE,#00,#02,#80
                defb #3F,#01,#FC,#00,#02,#E0,#0E,#07,#F0,#00,#02,#E0,#0F,#07,#70,#00
                defb #02,#E0,#0F,#07,#F0,#00,#02,#F0,#07,#0F,#E0,#00,#02,#F0,#07,#0F
                defb #E0,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#F0,#07,#07,#70,#00,#02,#F0,#07,#07,#70,#00
                defb #00,#00,#00
IDX_PLAYER_S3_JUMP_DOWN equ 19
gfx_player_s3_jump_down:
                defb #02,#14,#FF,#00,#02,#F8,#03,#1F,#C0,#00,#02,#F0,#07,#0F,#E0,#00
                defb #02,#F0,#07,#0F,#E0,#00,#02,#F0,#06,#0F,#60,#00,#02,#F8,#03,#1F
                defb #C0,#00,#02,#FC,#01,#3F,#80,#00,#02,#80,#3F,#01,#FC,#00,#02,#00
                defb #FF,#00,#FF,#00,#02,#00,#CE,#00,#F3,#00,#02,#E0,#0F,#07,#70,#00
                defb #02,#E0,#0F,#07,#F0,#00,#02,#F0,#07,#0F,#E0,#00,#02,#F0,#07,#0F
                defb #E0,#00,#02,#F8,#00,#1F,#00,#00,#02,#F0,#07,#07,#70,#00,#02,#F0
                defb #07,#07,#70,#00,#02,#E0,#0E,#83,#38,#00,#02,#E0,#0E,#83,#38,#00
                defb #02,#C1,#1C,#C1,#1C,#00,#02,#C1,#1C,#C1,#1C
IDX_PLAYER_S4_JUMP_UP equ 20
gfx_player_s4_jump_up:
                defb #04,#16,#FF,#01,#02,#F8,#03,#1F,#C0,#01,#02,#00,#67,#00,#E6,#01
                defb #02,#00,#67,#00,#E6,#01,#02,#00,#67,#00,#E6,#01,#02,#00,#66,#00
                defb #66,#01,#02,#08,#63,#10,#C6,#01,#02,#0C,#61,#30,#86,#01,#02,#00
                defb #7F,#00,#FE,#01,#02,#80,#3F,#01,#FC,#01,#02,#E0,#0E,#07,#F0,#01
                defb #02,#E0,#0F,#07,#70,#01,#02,#E0,#0F,#07,#F0,#01,#02,#F0,#07,#0F
                defb #E0,#01,#02,#F0,#07,#0F,#E0,#01,#02,#F8,#00,#1F,#00,#01,#02,#E0
                defb #0E,#07,#70,#01,#02,#E0,#0E,#07,#70,#01,#02,#E0,#0E,#07,#70,#01
                defb #02,#E0,#0E,#07,#70,#01,#02,#E0,#0E,#07,#70,#00,#00,#00,#00
IDX_PLAYER_S4_JUMP_DOWN equ 21
gfx_player_s4_jump_down:
                defb #04,#16,#FF,#01,#02,#F8,#03,#1F,#C0,#01,#02,#F0,#07,#0F,#E0,#01
                defb #02,#F0,#07,#0F,#E0,#01,#02,#F0,#07,#0F,#E0,#01,#02,#F0,#06,#0F
                defb #60,#01,#02,#F8,#03,#1F,#C0,#01,#02,#FC,#01,#3F,#80,#01,#02,#80
                defb #3F,#01,#FC,#00,#04,#FE,#00,#00,#FF,#00,#FF,#7F,#00,#00,#04,#FC
                defb #01,#00,#CE,#00,#F3,#3F,#80,#00,#04,#FC,#01,#60,#0F,#06,#70,#3F
                defb #80,#01,#02,#E0,#0F,#07,#F0,#01,#02,#F0,#07,#0F,#E0,#01,#02,#F0
                defb #07,#0F,#E0,#01,#02,#F8,#00,#1F,#00,#01,#02,#E0,#0E,#07,#70,#01
                defb #02,#E0,#0E,#07,#70,#01,#02,#C1,#1C,#83,#38,#01,#02,#C1,#1C,#83
                defb #38,#01,#02,#83,#38,#C1,#1C,#01,#02,#83,#38,#C1,#1C,#01,#02,#07
                defb #70,#E0,#0E
IDX_PLAYER_S5_JUMP equ 22
gfx_player_s5_jump:
                defb #04,#18,#FF,#01,#02,#F8,#03,#1F,#C0,#01,#02,#F0,#07,#0F,#E0,#01
                defb #02,#F0,#07,#0F,#E0,#01,#02,#F0,#07,#0F,#E0,#01,#02,#F0,#06,#0F
                defb #60,#01,#02,#F8,#03,#1F,#C0,#01,#02,#FC,#01,#3F,#80,#01,#02,#00
                defb #7F,#00,#FE,#00,#04,#FC,#01,#00,#FF,#00,#FF,#3F,#80,#00,#04,#F8
                defb #03,#00,#9E,#00,#F9,#1F,#C0,#00,#04,#F8,#02,#C0,#1F,#03,#78,#1F
                defb #40,#01,#02,#C0,#1F,#03,#F8,#01,#02,#C0,#1F,#03,#F8,#01,#02,#E0
                defb #0F,#07,#F0,#01,#02,#E0,#0F,#07,#F0,#01,#02,#F0,#00,#0F,#00,#01
                defb #02,#E0,#0E,#07,#70,#01,#02,#E0,#0E,#07,#70,#01,#02,#C1,#1C,#83
                defb #38,#01,#02,#C1,#1C,#83,#38,#01,#02,#83,#38,#C1,#1C,#01,#02,#83
                defb #38,#C1,#1C,#01,#02,#07,#70,#E0,#0E,#01,#02,#07,#70,#E0,#0E
gfx_shadows_table:
                defw gfx_shadows_sh2
                defw gfx_shadows_sh3
IDX_SHADOWS_SH2 equ 0
gfx_shadows_sh2:
                defb #02,#04,#FF,#00,#02,#FA,#00,#AF,#00,#00,#02,#D5,#00,#57,#00,#00
                defb #02,#EA,#00,#AB,#00,#00,#02,#F5,#00,#5F,#00
IDX_SHADOWS_SH3 equ 1
gfx_shadows_sh3:
                defb #02,#06,#FF,#00,#02,#FA,#00,#AF,#00,#00,#02,#D5,#00,#57,#00,#00
                defb #02,#AA,#00,#AB,#00,#00,#02,#D5,#00,#55,#00,#00,#02,#EA,#00,#AB
                defb #00,#00,#02,#F5,#00,#5F,#00
