; generated by tools/zxgfx.py from tools/zxart.py - do not edit
HUD_INK_COIN equ #46
gfx_hud_coin:
                defb #3C,#66,#DB,#DF,#DF,#DB,#66,#3C
HUD_INK_LIFE equ #42
gfx_hud_life:
                defb #00,#66,#FF,#FF,#7E,#3C,#18,#00
HUD_INK_MAGNET equ #42
gfx_hud_magnet:
                defb #C3,#C3,#C3,#C3,#E7,#7E,#3C,#00
HUD_INK_TURBO equ #46
gfx_hud_turbo:
                defb #18,#3C,#66,#DB,#3C,#66,#C3,#00
HUD_INK_SLOW equ #45
gfx_hud_slow:
                defb #FF,#42,#3C,#18,#18,#24,#7E,#FF
HUD_INK_SPRING equ #44
gfx_hud_spring:
                defb #FE,#03,#7E,#C0,#7E,#03,#FE,#00
HUD_INK_HELMET equ #46
gfx_hud_helmet:
                defb #3C,#7E,#FF,#FF,#FF,#00,#FF,#00
HUD_INK_TICKET equ #47
gfx_hud_ticket:
                defb #FF,#81,#B5,#95,#A3,#B5,#81,#FF
gfx_hud_rail:
                defb #FF,#42,#42,#42,#FF,#42,#42,#42
