; generated by tools/mkmusic.py from music/*.txt - do not edit
BEEP_LOOP_T equ 26
BEEP_EXTRA_T equ 67
TUNE_LOOP equ #FF
TUNE_STOP equ #FE
SFX_END equ #FF
SFX_TONE_OFF equ #80
SFX_NOISE_ON equ #40
TUNE_GAME equ 0
TUNE_MENU equ 1
TUNE_OVER equ 2
SFX_COIN equ 1
SFX_JUMP equ 2
SFX_SIGNAL equ 3
SFX_POWERUP equ 4
SFX_CRASH equ 5
note_periods:                       ; note 1 = C2
                defw 1695,1599,1510,1425,1345,1270,1198,1131,1068,1008,951,898
                defw 847,800,755,712,673,635,599,566,534,504,476,449
                defw 424,400,377,356,336,317,300,283,267,252,238,224
                defw 212,200,189,178,168,159,150,141,133,126,119,112
                defw 106,100,94,89,84,79,75,71,67,63,59,56
                defw 53,50,47,45,42,40,37,35,33,31,30,28
beep_counts:                        ; note 1 = C2
                defw 1026,969,914,863,814,768,725,684,646,609,575,543
                defw 512,483,456,430,406,383,361,341,322,303,286,270
                defw 255,240,227,214,202,190,179,169,159,150,142,134
                defw 126,119,112,106,100,94,88,83,78,74,70,66
                defw 62,58,55,52,48,46,43,40,38,36,34,31
                defw 30,28,26,24,23,22,20,19,18,17,15,14
tune_table:                         ; channel A, channel B
                defw tune_game_a,tune_game_b
                defw tune_menu_a,tune_menu_b
                defw tune_over_a,tune_over_b
tune_game_a:
                defb 34,8,35,8,38,8,39,8,41,16,41,16,42,8,41,8
                defb 39,8,38,8,39,16,0,16,41,8,39,8,38,8,35,8
                defb 38,16,34,16,35,8,34,8,33,8,35,8,34,32,46,8
                defb 45,8,42,8,41,8,42,16,41,16,39,8,41,8,42,8
                defb 45,8,46,16,0,16,45,8,42,8,41,8,39,8,38,8
                defb 39,8,41,8,38,8,39,8,38,8,35,8,38,8,34,32
                defb #FF
tune_game_b:
                defb 10,16,17,16,10,16,17,16,15,16,10,16,15,16,10,16
                defb 10,16,17,16,10,16,17,16,11,16,18,16,10,16,17,16
                defb 15,16,10,16,15,16,10,16,17,16,12,16,17,16,9,16
                defb 10,16,17,16,10,16,17,16,11,16,18,16,10,16,17,16
                defb #FF
tune_menu_a:
                defb 39,20,41,10,42,10,41,20,39,20,38,20,39,10,41,10
                defb 34,40,35,20,34,10,32,10,34,20,35,20,38,20,35,10
                defb 34,10,34,40,42,20,41,10,39,10,41,20,42,20,44,20
                defb 42,10,41,10,39,40,41,10,42,10,41,10,39,10,38,20
                defb 35,20,34,20,38,20,39,40
                defb #FF
tune_menu_b:
                defb 15,40,10,40,10,40,17,40,8,40,15,40,10,40,17,40
                defb 15,40,10,40,8,40,15,40,10,40,17,40,15,40,10,40
                defb #FF
tune_over_a:
                defb 46,6,45,6,42,6,41,6,39,6,38,6,35,6,38,6
                defb 34,36,0,12
                defb #FE
tune_over_b:
                defb 10,12,15,12,11,12,17,12,10,36,0,12
                defb #FE
sfx_table:                          ; steps, priority
                defw sfx_steps_coin
                defb 1
                defw sfx_steps_jump
                defb 1
                defw sfx_steps_signal
                defb 1
                defw sfx_steps_powerup
                defb 2
                defw sfx_steps_crash
                defb 3
sfx_steps_coin:
                defw 112
                defb #0D,0
                defw 34
                defb 2
                defw 84
                defb #0D,0
                defw 48
                defb 1
                defw 84
                defb #0B,0
                defw 48
                defb 1
                defw 84
                defb #09,0
                defw 48
                defb 1
                defw 84
                defb #06,0
                defw 48
                defb 1
                defw 84
                defb #03,0
                defw 48
                defb 1
                defw 0
                defb #FF,0
                defw 0
                defb 0
sfx_steps_jump:
                defw 424
                defb #0C,0
                defw 33
                defb 2
                defw 336
                defb #0C,0
                defw 52
                defb 1
                defw 283
                defb #0B,0
                defw 43
                defb 1
                defw 212
                defb #0A,0
                defw 33
                defb 2
                defw 168
                defb #08,0
                defw 51
                defb 1
                defw 141
                defb #06,0
                defw 42
                defb 1
                defw 0
                defb #FF,0
                defw 0
                defb 0
sfx_steps_signal:
                defw 71
                defb #0C,0
                defw 40
                defb 1
                defw 71
                defb #0B,0
                defw 40
                defb 1
                defw 71
                defb #0A,0
                defw 40
                defb 1
                defw 71
                defb #09,0
                defw 40
                defb 1
                defw 71
                defb #07,0
                defw 40
                defb 1
                defw 84
                defb #0C,0
                defw 48
                defb 1
                defw 84
                defb #0B,0
                defw 48
                defb 1
                defw 84
                defb #0A,0
                defw 48
                defb 1
                defw 84
                defb #09,0
                defw 48
                defb 1
                defw 84
                defb #08,0
                defw 48
                defb 1
                defw 84
                defb #06,0
                defw 48
                defb 1
                defw 84
                defb #04,0
                defw 48
                defb 1
                defw 0
                defb #FF,0
                defw 0
                defb 0
sfx_steps_powerup:
                defw 126
                defb #0D,0
                defw 38
                defb 1
                defw 126
                defb #0D,0
                defw 38
                defb 1
                defw 100
                defb #0D,0
                defw 58
                defb 1
                defw 100
                defb #0D,0
                defw 58
                defb 1
                defw 84
                defb #0D,0
                defw 48
                defb 1
                defw 84
                defb #0D,0
                defw 48
                defb 1
                defw 63
                defb #0D,0
                defw 36
                defb 1
                defw 63
                defb #0C,0
                defw 36
                defb 1
                defw 63
                defb #0B,0
                defw 36
                defb 1
                defw 63
                defb #0A,0
                defw 36
                defb 1
                defw 63
                defb #08,0
                defw 36
                defb 1
                defw 63
                defb #06,0
                defw 36
                defb 1
                defw 63
                defb #04,0
                defw 36
                defb 1
                defw 0
                defb #FF,0
                defw 0
                defb 0
sfx_steps_crash:
                defw 1008
                defb #4F,31
                defw 39
                defb 1
                defw 1008
                defb #4F,28
                defw 39
                defb 1
                defw 0
                defb #CE,24
                defw 0
                defb 0
                defw 0
                defb #CD,20
                defw 0
                defb 0
                defw 0
                defb #CC,18
                defw 0
                defb 0
                defw 0
                defb #CB,16
                defw 0
                defb 0
                defw 0
                defb #CA,14
                defw 0
                defb 0
                defw 0
                defb #C9,12
                defw 0
                defb 0
                defw 0
                defb #C8,12
                defw 0
                defb 0
                defw 0
                defb #C7,12
                defw 0
                defb 0
                defw 0
                defb #C6,12
                defw 0
                defb 0
                defw 0
                defb #C5,12
                defw 0
                defb 0
                defw 0
                defb #C4,12
                defw 0
                defb 0
                defw 0
                defb #C3,12
                defw 0
                defb 0
                defw 0
                defb #C2,12
                defw 0
                defb 0
                defw 0
                defb #FF,0
                defw 0
                defb 0
