; generated by tools/mktext.py from text/*.txt - do not edit
text_ptr_tables:
                defw text_ptrs_en
                defw text_ptrs_el
text_ptrs_en:
                defw text_en_menu_start
                defw text_en_menu_controls
                defw text_en_menu_scores
                defw text_en_menu_skill_0
                defw text_en_menu_skill_1
                defw text_en_menu_skill_2
                defw text_en_menu_music_off
                defw text_en_menu_music_on
                defw text_en_menu_sound_off
                defw text_en_menu_sound_on
                defw text_en_menu_hint
                defw text_en_menu_lang
                defw text_en_menu_credit
                defw text_en_menu_credit2
                defw text_en_menu_credit3
                defw text_en_controls_title
                defw text_en_controls_left
                defw text_en_controls_right
                defw text_en_controls_jump
                defw text_en_controls_down
                defw text_en_controls_pause
                defw text_en_controls_esc
                defw text_en_controls_music
                defw text_en_controls_joy
                defw text_en_controls_back
                defw text_en_scores_title
                defw text_en_over_title
                defw text_en_over_score
                defw text_en_over_coins
                defw text_en_over_dist
                defw text_en_over_record
                defw text_en_over_name
                defw text_en_over_name_hint
                defw text_en_over_continue
                defw text_en_pause
                defw text_en_demo
                defw text_en_pu_magnet
                defw text_en_pu_turbo
                defw text_en_pu_slow
                defw text_en_pu_spring
                defw text_en_pu_helmet
                defw text_en_pu_ticket
                defw text_en_pu_wagons
                defw text_en_pu_3
                defw text_en_pu_2
                defw text_en_pu_1
                defw text_en_pu_go
                defw text_en_station_1
                defw text_en_station_2
                defw text_en_station_3
                defw text_en_station_4
                defw text_en_station_5
                defw text_en_station_6
                defw text_en_menu_story
                defw text_en_story_title
                defw text_en_story_1
                defw text_en_story_2
                defw text_en_story_3
                defw text_en_story_4
                defw text_en_story_5
                defw text_en_story_6
                defw text_en_story_7
                defw text_en_story_8
                defw text_en_story_9
                defw text_en_story_10
                defw text_en_story_11
                defw text_en_story_12
                defw text_en_story_13
                defw text_en_story_14
                defw text_en_story_15
text_ptrs_el:
                defw text_el_menu_start
                defw text_el_menu_controls
                defw text_el_menu_scores
                defw text_el_menu_skill_0
                defw text_el_menu_skill_1
                defw text_el_menu_skill_2
                defw text_el_menu_music_off
                defw text_el_menu_music_on
                defw text_el_menu_sound_off
                defw text_el_menu_sound_on
                defw text_el_menu_hint
                defw text_el_menu_lang
                defw text_el_menu_credit
                defw text_el_menu_credit2
                defw text_el_menu_credit3
                defw text_el_controls_title
                defw text_el_controls_left
                defw text_el_controls_right
                defw text_el_controls_jump
                defw text_el_controls_down
                defw text_el_controls_pause
                defw text_el_controls_esc
                defw text_el_controls_music
                defw text_el_controls_joy
                defw text_el_controls_back
                defw text_el_scores_title
                defw text_el_over_title
                defw text_el_over_score
                defw text_el_over_coins
                defw text_el_over_dist
                defw text_el_over_record
                defw text_el_over_name
                defw text_el_over_name_hint
                defw text_el_over_continue
                defw text_el_pause
                defw text_el_demo
                defw text_el_pu_magnet
                defw text_el_pu_turbo
                defw text_el_pu_slow
                defw text_el_pu_spring
                defw text_el_pu_helmet
                defw text_el_pu_ticket
                defw text_el_pu_wagons
                defw text_el_pu_3
                defw text_el_pu_2
                defw text_el_pu_1
                defw text_el_pu_go
                defw text_el_station_1
                defw text_el_station_2
                defw text_el_station_3
                defw text_el_station_4
                defw text_el_station_5
                defw text_el_station_6
                defw text_el_menu_story
                defw text_el_story_title
                defw text_el_story_1
                defw text_el_story_2
                defw text_el_story_3
                defw text_el_story_4
                defw text_el_story_5
                defw text_el_story_6
                defw text_el_story_7
                defw text_el_story_8
                defw text_el_story_9
                defw text_el_story_10
                defw text_el_story_11
                defw text_el_story_12
                defw text_el_story_13
                defw text_el_story_14
                defw text_el_story_15
text_en_menu_start:
                defb 19,20,1,18,20,255
text_en_menu_controls:
                defb 3,15,14,20,18,15,12,19,255
text_en_menu_scores:
                defb 8,9,7,8,0,19,3,15,18,5,19,255
text_en_menu_skill_0:
                defb 4,9,6,6,9,3,21,12,20,25,48,0,5,1,19,25,255
text_en_menu_skill_1:
                defb 4,9,6,6,9,3,21,12,20,25,48,0,13,5,4,9,21,13,255
text_en_menu_skill_2:
                defb 4,9,6,6,9,3,21,12,20,25,48,0,8,1,18,4,255
text_en_menu_music_off:
                defb 13,21,19,9,3,48,0,15,6,6,255
text_en_menu_music_on:
                defb 13,21,19,9,3,48,0,15,14,255
text_en_menu_sound_off:
                defb 19,15,21,14,4,48,0,15,6,6,255
text_en_menu_sound_on:
                defb 19,15,21,14,4,48,0,15,14,255
text_en_menu_hint:
                defb 17,0,1,0,1,14,4,0,19,16,1,3,5,255
text_en_menu_lang:
                defb 12,0,48,0,5,40,40,8,14,9,11,1,255
text_en_menu_credit:
                defb 1,20,8,5,14,19,0,16,9,18,1,5,21,19,255
text_en_menu_credit2:
                defb 5,12,5,3,20,18,9,3,0,18,1,9,12,23,1,25,19,255
text_en_menu_credit3:
                defb 18,5,22,9,22,5,35,2,9,20,49,29,27,29,33,49,22,1,19,16,5,18,255
text_en_controls_title:
                defb 3,15,14,20,18,15,12,19,255
text_en_controls_left:
                defb 15,0,48,0,12,5,6,20,255
text_en_controls_right:
                defb 16,0,48,0,18,9,7,8,20,255
text_en_controls_jump:
                defb 17,0,15,18,0,19,16,1,3,5,0,48,0,10,21,13,16,255
text_en_controls_down:
                defb 1,0,48,0,4,15,23,14,255
text_en_controls_pause:
                defb 8,0,48,0,16,1,21,19,5,255
text_en_controls_esc:
                defb 2,18,5,1,11,0,48,0,13,5,14,21,255
text_en_controls_music:
                defb 13,0,48,0,13,21,19,9,3,0,15,14,52,15,6,6,255
text_en_controls_joy:
                defb 15,18,0,11,5,13,16,19,20,15,14,0,52,0,19,9,14,3,12,1,9,18,255
text_en_controls_back:
                defb 19,16,1,3,5,0,48,0,2,1,3,11,255
text_en_scores_title:
                defb 8,9,7,8,0,19,3,15,18,5,19,255
text_en_over_title:
                defb 7,1,13,5,0,15,22,5,18,255
text_en_over_score:
                defb 19,3,15,18,5,255
text_en_over_coins:
                defb 3,15,9,14,19,255
text_en_over_dist:
                defb 4,9,19,20,1,14,3,5,255
text_en_over_record:
                defb 14,5,23,0,8,9,7,8,0,19,3,15,18,5,50,255
text_en_over_name:
                defb 14,1,13,5,48,255
text_en_over_name_hint:
                defb 17,0,1,0,12,5,20,20,5,18,0,0,19,16,1,3,5,0,15,11,255
text_en_over_continue:
                defb 19,16,1,3,5,0,48,0,3,15,14,20,9,14,21,5,255
text_en_pause:
                defb 16,1,21,19,5,255
text_en_demo:
                defb 4,5,13,15,255
text_en_pu_magnet:
                defb 13,1,7,14,5,20,255
text_en_pu_turbo:
                defb 20,21,18,2,15,255
text_en_pu_slow:
                defb 19,12,15,23,255
text_en_pu_spring:
                defb 19,21,16,5,18,0,10,21,13,16,255
text_en_pu_helmet:
                defb 8,5,12,13,5,20,255
text_en_pu_ticket:
                defb 29,24,0,3,15,9,14,19,255
text_en_pu_wagons:
                defb 10,21,13,16,0,2,5,20,23,5,5,14,0,23,1,7,15,14,19,50,255
text_en_pu_3:
                defb 30,255
text_en_pu_2:
                defb 29,255
text_en_pu_1:
                defb 28,255
text_en_pu_go:
                defb 7,15,50,255
text_en_station_1:
                defb 3,15,18,9,14,20,8,255
text_en_station_2:
                defb 13,5,7,1,18,1,255
text_en_station_3:
                defb 5,12,5,6,19,9,14,1,255
text_en_station_4:
                defb 1,19,16,18,15,16,25,18,7,15,19,255
text_en_station_5:
                defb 18,5,14,20,9,19,255
text_en_station_6:
                defb 16,9,18,1,5,21,19,50,0,28,27,27,27,0,2,15,14,21,19,255
text_en_menu_story:
                defb 19,20,15,18,25,255
text_en_story_title:
                defb 20,8,5,0,12,1,19,20,0,19,15,21,22,12,1,11,9,0,13,1,14,255
text_en_story_1:
                defb 33,48,31,34,0,1,13,0,9,14,0,11,9,1,20,15,47,255
text_en_story_2:
                defb 21,14,3,12,5,0,2,1,2,9,19,0,16,1,14,9,3,19,48,0,20,8,5,255
text_en_story_3:
                defb 19,15,21,22,12,1,11,9,0,10,21,4,7,5,0,3,15,13,5,19,0,1,20,255
text_en_story_4:
                defb 14,15,15,14,0,49,0,1,14,4,0,20,8,5,0,19,5,3,18,5,20,255
text_en_story_5:
                defb 19,16,9,3,5,0,9,19,0,19,20,9,12,12,0,9,14,0,11,9,1,20,15,50,255
text_en_story_6:
                defb 255
text_en_story_7:
                defb 14,15,0,20,18,1,9,14,48,0,1,0,7,15,1,20,0,15,14,0,20,8,5,255
text_en_story_8:
                defb 12,9,14,5,47,0,14,15,0,20,1,24,9,48,0,2,1,2,9,19,0,9,19,255
text_en_story_9:
                defb 20,8,5,0,15,14,12,25,0,20,1,24,9,0,4,18,9,22,5,18,47,255
text_en_story_10:
                defb 255
text_en_story_11:
                defb 10,21,13,16,0,20,8,5,0,19,20,15,16,19,47,0,7,18,1,2,0,20,8,5,255
text_en_story_12:
                defb 3,15,9,14,19,47,0,20,8,5,0,9,14,19,16,5,3,20,15,18,0,1,14,4,255
text_en_story_13:
                defb 20,8,5,0,7,15,1,20,0,1,18,5,0,1,6,20,5,18,0,25,15,21,47,255
text_en_story_14:
                defb 14,15,0,19,16,9,3,5,51,0,19,21,16,5,18,13,1,18,11,5,20,255
text_en_story_15:
                defb 15,18,5,7,1,14,15,47,0,14,5,22,5,18,50,0,18,21,14,50,255
text_el_menu_start:
                defb 5,14,1,16,41,8,255
text_el_menu_controls:
                defb 24,5,9,16,9,43,13,15,9,255
text_el_menu_scores:
                defb 16,5,11,15,16,255
text_el_menu_skill_0:
                defb 38,25,43,11,15,40,9,1,48,0,5,25,11,15,40,15,255
text_el_menu_skill_1:
                defb 38,25,43,11,15,40,9,1,48,0,13,5,20,16,9,15,255
text_el_menu_skill_2:
                defb 38,25,43,11,15,40,9,1,48,0,38,25,43,11,15,40,15,255
text_el_menu_music_off:
                defb 13,15,25,43,9,11,8,48,0,15,24,9,255
text_el_menu_music_on:
                defb 13,15,25,43,9,11,8,48,0,14,1,9,255
text_el_menu_sound_off:
                defb 8,24,15,43,48,0,15,24,9,255
text_el_menu_sound_on:
                defb 8,24,15,43,48,0,14,1,9,255
text_el_menu_hint:
                defb 17,0,1,0,11,1,9,0,19,16,1,3,5,255
text_el_menu_lang:
                defb 12,0,48,0,5,14,7,12,9,19,8,255
text_el_menu_credit:
                defb 1,20,8,5,14,19,0,16,9,18,1,5,21,19,255
text_el_menu_credit2:
                defb 5,12,5,3,20,18,9,3,0,18,1,9,12,23,1,25,19,255
text_el_menu_credit3:
                defb 18,5,22,9,22,5,35,2,9,20,49,29,27,29,33,49,22,1,19,16,5,18,255
text_el_controls_title:
                defb 24,5,9,16,9,43,13,15,9,255
text_el_controls_left:
                defb 15,0,48,0,1,16,9,43,20,5,16,1,255
text_el_controls_right:
                defb 16,0,48,0,38,5,41,9,1,255
text_el_controls_jump:
                defb 17,0,8,0,19,16,1,3,5,0,48,0,1,40,13,1,255
text_el_controls_down:
                defb 1,0,48,0,11,1,20,46,255
text_el_controls_pause:
                defb 8,0,48,0,42,1,25,43,8,255
text_el_controls_esc:
                defb 2,18,5,1,11,0,48,0,13,5,14,15,25,255
text_el_controls_music:
                defb 13,0,48,0,13,15,25,43,9,11,8,255
text_el_controls_joy:
                defb 8,0,11,5,13,16,19,20,15,14,0,52,0,19,9,14,3,12,1,9,18,255
text_el_controls_back:
                defb 19,16,1,3,5,0,48,0,42,9,43,46,255
text_el_scores_title:
                defb 16,5,11,15,16,255
text_el_over_title:
                defb 20,5,40,15,43,0,42,1,9,24,14,9,38,9,15,25,255
text_el_over_score:
                defb 43,11,15,16,255
text_el_over_coins:
                defb 14,15,13,9,43,13,1,20,1,255
text_el_over_dist:
                defb 1,42,15,43,20,1,43,8,255
text_el_over_record:
                defb 14,5,15,0,16,5,11,15,16,50,255
text_el_over_name:
                defb 15,14,15,13,1,48,255
text_el_over_name_hint:
                defb 17,0,1,0,37,16,1,13,13,1,0,0,19,16,1,3,5,0,15,11,255
text_el_over_continue:
                defb 19,16,1,3,5,0,48,0,43,25,14,5,24,5,9,1,255
text_el_pause:
                defb 42,1,25,43,8,255
text_el_demo:
                defb 4,5,13,15,255
text_el_pu_magnet:
                defb 13,1,37,14,8,20,8,43,255
text_el_pu_turbo:
                defb 20,15,25,16,13,42,15,255
text_el_pu_slow:
                defb 1,16,37,1,255
text_el_pu_spring:
                defb 25,42,5,16,1,40,13,1,255
text_el_pu_helmet:
                defb 11,16,1,14,15,43,255
text_el_pu_ticket:
                defb 29,24,0,11,5,16,13,1,20,1,255
text_el_pu_wagons:
                defb 42,8,38,1,0,1,14,1,13,5,43,1,0,43,20,1,0,2,1,37,15,14,9,1,255
text_el_pu_3:
                defb 30,255
text_el_pu_2:
                defb 29,255
text_el_pu_1:
                defb 28,255
text_el_pu_go:
                defb 42,1,13,5,50,255
text_el_station_1:
                defb 11,15,16,9,14,39,15,43,255
text_el_station_2:
                defb 13,5,37,1,16,1,255
text_el_station_3:
                defb 5,40,5,25,43,9,14,1,255
text_el_station_4:
                defb 1,43,42,16,15,42,25,16,37,15,43,255
text_el_station_5:
                defb 16,5,14,20,8,43,255
text_el_station_6:
                defb 42,5,9,16,1,9,1,43,50,0,28,27,27,27,0,42,15,14,20,15,9,255
text_el_menu_story:
                defb 9,43,20,15,16,9,1,255
text_el_story_title:
                defb 15,0,20,5,40,5,25,20,1,9,15,43,0,43,15,25,2,40,1,20,26,8,43,255
text_el_story_1:
                defb 33,48,31,34,0,20,15,0,42,16,46,9,0,43,20,15,0,11,9,1,20,15,47,255
text_el_story_2:
                defb 15,0,39,5,9,15,43,0,13,42,1,13,42,8,43,0,42,1,14,9,11,15,43,48,255
text_el_story_3:
                defb 15,0,11,16,9,20,8,43,0,20,15,25,0,43,15,25,2,40,1,11,9,15,25,255
text_el_story_4:
                defb 5,16,24,5,20,1,9,0,43,20,9,43,0,28,29,48,27,27,0,11,1,9,255
text_el_story_5:
                defb 20,15,0,13,42,1,24,1,16,9,11,15,0,5,9,14,1,9,0,5,38,46,50,255
text_el_story_6:
                defb 255
text_el_story_7:
                defb 20,16,5,14,15,0,38,5,14,0,5,24,5,9,48,0,11,1,20,43,9,11,1,255
text_el_story_8:
                defb 43,20,8,0,37,16,1,13,13,8,47,0,20,1,41,9,0,15,25,20,5,48,255
text_el_story_9:
                defb 15,0,20,1,41,9,20,26,8,43,0,5,9,14,1,9,0,1,25,20,15,43,47,255
text_el_story_10:
                defb 255
text_el_story_11:
                defb 42,8,38,1,0,20,1,0,43,20,15,42,47,0,13,1,26,5,45,5,0,20,1,255
text_el_story_12:
                defb 11,5,16,13,1,20,1,47,0,15,0,5,40,5,37,11,20,8,43,0,11,1,9,255
text_el_story_13:
                defb 8,0,11,1,20,43,9,11,1,0,43,5,0,11,25,14,8,37,1,14,5,47,255
text_el_story_14:
                defb 24,46,16,9,43,0,13,42,1,24,1,16,9,11,15,48,0,16,9,37,1,14,8,255
text_el_story_15:
                defb 43,15,25,42,5,16,0,13,1,16,11,5,20,47,0,20,16,5,41,5,50,255
